/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package duplicated.characters.app;

public class App {
    public static void main(String[] args) {
        String word = "AABBCCD112233";
        String result = StringProcessor.removeDuplicates(word);
        System.out.println(result);

    }
}
