/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package duplicated.characters.app;

import java.util.LinkedHashSet;
import java.util.Set;

public class StringProcessor {

    public static String removeDuplicates(String input) {

        if (input == null){
            return null;
        }

        Set<Character> chars = new LinkedHashSet<>();
        for (char c : input.toCharArray()) {
            chars.add(c);
        }

        StringBuilder sb = new StringBuilder();
        for (char c : chars) {
            sb.append(c);
        }

        return sb.toString();
    }
}